"""Add file upload, edit, delete, push notification features

Revision ID: 1c7ab1312c78
Revises: abfe725dfafe
Create Date: 2025-11-29 10:17:46.931991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7ab1312c78'
down_revision = 'abfe725dfafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- تغییر مهم: این بخش کامنت شد چون جدول قبلا وجود دارد ---
    # op.create_table('push_subscription',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('endpoint', sa.String(length=500), nullable=False),
    # sa.Column('p256dh', sa.String(length=500), nullable=False),
    # sa.Column('auth', sa.String(length=500), nullable=False),
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ---------------------------------------------------------

    # دستورات زیر باید اجرا شوند تا ستون‌های جدید اضافه شوند
    # استفاده از try/except برای جلوگیری از خطای احتمالی اگر ستون‌ها هم قبلا ساخته شده باشند
    try:
        op.add_column('message', sa.Column('edited_at', sa.DateTime(), nullable=True))
        op.add_column('message', sa.Column('is_deleted', sa.Boolean(), nullable=True))
        op.add_column('message', sa.Column('file_path', sa.String(length=500), nullable=True))
        op.add_column('message', sa.Column('file_name', sa.String(length=255), nullable=True))
        op.add_column('message', sa.Column('file_type', sa.String(length=50), nullable=True))
        op.add_column('message', sa.Column('file_size', sa.Integer(), nullable=True))
    except Exception:
        pass # اگر این ستون‌ها بودند، خطا را نادیده بگیر

    # ایندکس‌ها
    try:
        op.create_index('idx_sender_receiver_timestamp', 'message', ['sender_id', 'receiver_id', 'timestamp'], unique=False)
        op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    except Exception:
        pass

    # اضافه کردن ستون theme که باعث خطای اول شما شده بود
    try:
        op.add_column('user', sa.Column('theme', sa.String(length=20), nullable=True))
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'theme')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_index('idx_sender_receiver_timestamp', table_name='message')
    op.drop_column('message', 'file_size')
    op.drop_column('message', 'file_type')
    op.drop_column('message', 'file_name')
    op.drop_column('message', 'file_path')
    op.drop_column('message', 'is_deleted')
    op.drop_column('message', 'edited_at')
    op.drop_table('push_subscription')
    # ### end Alembic commands ###